### ISSUE TITLE
ML kit scanner not working on Samsung galaxy S20 FE 5G

### ISSUE THREAD

**Issue by jca1981** [patzly/grocy-android-unlock#3]
hi i am trying to get the ML kit scanner working after buying the unlock app.
the app freezes every time i enable it and try to scan, scan window is just black.
i have tried disabling / enable chop camera, but still freezes.
i have also tried rebooting
i am using a Samsung galaxy S20 FE 5G

**Comment by patzly** [comment]
Hi, can you please download the latest nightly build from the main repo and try it again? Please open a new issue in the main repo if it's still not working. Issues with scanning are about the main app, the unlock key is just a key to unlock that functionality.

**Comment by dfriday** [comment]
Had the same bug on Pixel 6 Xl. Manually enabling the permission for notifications fixed it for me. I was never prompted to enable notifications inside the app.

**Comment by jca1981** [comment]
it is fixed for me now. app sometimes still closes when scanning but not
very often.

Den lør. 7. jan. 2023 kl. 12.26 skrev dfriday ***@***.***>:
